#define NV_CRYPTO_PRESENT
#define NV_CRYPTO_AKCIPHER_VERIFY_PRESENT
#undef NV_DMA_BUF_OPS_ATTACH_ARG2_DEV
#define NV_ECC_DIGITS_FROM_BYTES_PRESENT
#undef NV_FOLLOW_PTE_ARG1_VMA
#define NV_IS_EXPORT_SYMBOL_GPL_iommu_dev_disable_feature 1
#define NV_IS_EXPORT_SYMBOL_GPL_iommu_dev_enable_feature 1
#define NV_IS_EXPORT_SYMBOL_GPL_mutex_destroy 1
#define NV_IS_EXPORT_SYMBOL_GPL_pci_ats_supported 1
#define NV_IS_EXPORT_SYMBOL_GPL_platform_device_put 1
#define NV_IS_EXPORT_SYMBOL_GPL___platform_driver_register 1
#define NV_IS_EXPORT_SYMBOL_GPL_screen_info 1
#define NV_IS_EXPORT_SYMBOL_GPL_set_memory_decrypted 0
#define NV_IS_EXPORT_SYMBOL_GPL_set_memory_encrypted 0
#define NV_IS_EXPORT_SYMBOL_GPL_sme_active 0
#define NV_IS_EXPORT_SYMBOL_GPL___vma_start_write 0
#define NV_IS_EXPORT_SYMBOL_PRESENT___close_fd 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_close_fd 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_follow_pfnmap_start 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_follow_pte 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_hrtimer_setup 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_i2c_bus_status 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_lockdep_register_key 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_memory_block_size_bytes 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_pci_find_host_bridge 1
#define NV_IS_EXPORT_SYMBOL_PRESENT___platform_driver_register 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_pxm_to_node 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_screen_info 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_swiotlb_dma_ops 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_swiotlb_map_sg_attrs 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tegra_fuse_control_read 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_timer_delete_sync 1
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_alloc_mem_from_gscco 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_clear_init_cb 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_free_gscco_mem 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_send_cmd 0
#define NV_IS_EXPORT_SYMBOL_PRESENT_tsec_comms_set_init_cb 0
